#spring.application.name=database
#spring.datasource.url=jdbc:postgresql://localhost:5432/college_database
#spring.datasource.username=postgres
#spring.datasource.password=201024
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#logging.level.org.springframework.http.converter.json=TRACE
#logging.level.com.fasterxml.jackson.databind=TRACE
#server.error.include-message=always
#server.error.include-stacktrace=always


spring.application.name=database

server.port=${PORT:5432}

spring.datasource.url=${postgresql://attendance_database_wisz_user:laSoGg5HHOIonAz8BZLv0tdeD7oaXNLp@dpg-d9pnhht3erlc7397lba0-a/attendance_database_wisz}
spring.datasource.username=${attendance_database_wisz_user}
spring.datasource.password=${laSoGg5HHOIonAz8BZLv0tdeD7oaXNLp}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.http.converter.json=TRACE
logging.level.com.fasterxml.jackson.databind=TRACE

server.error.include-message=always
server.error.include-stacktrace=always

